spring.application.name=vestry-api

tiingo.api.token=${TIINGO_API_TOKEN}

# Database
spring.datasource.url=${RDS_URL}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

## update -- update at deploy
## create -- create tables at deploy
## create-drop -- create tables at deploy and drop at shutdown
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port = 5000
